---
name: LevelsCore
main: kyng\Levels\Main
author: kyng
version: 1.0.0
api: [3.0.0-ALPHA10, 3.0.0-ALPHA11, 3.0.0-ALPHA12, 4.0.0]
description: level plugin.
commands:
 stats:
  description: Shows your current stats!
  usage: /stats
  aliases: [st]
 addexp:
  description: Add experience to a player!
  usage: /addexp <player> <exp>
  aliases: [aexp]
 reduceexp:
  description: Reduce a player's experience!
  usage: /reduceexp <player> <exp>
  aliaess: [rexp]
 levelup:
  description: Level up with your current experience!
  usage: /levelup 
  aliases: [lu, levup, level, up]
...
